package core;

import java.util.List;

/**
 * Immutable result value for the RAG {@code ask} operation.
 *
 * <p>Returned by {@link LibraryService#ask(String)}: contains the
 * LLM-generated, catalogue-grounded answer together with the text
 * chunks that were retrieved from the vector store and used as context.
 *
 * @param answer  The grounded natural-language answer generated by the
 *                chat model (never null; may be an empty string when the
 *                model returns no content).
 * @param sources The top-k document chunks retrieved from the vector store
 *                that were injected as context into the prompt. May be empty
 *                if the vector store has not been indexed yet.
 *
 * @author JuanGS (workstream b — RAG core)
 */
public record AnswerWithSources(String answer, List<String> sources) {

    public AnswerWithSources {
        answer  = answer  != null ? answer  : "";
        sources = sources != null ? List.copyOf(sources) : List.of();
    }
}
